version: "3.9"
services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: shopping_cart_db
    ports:
      - "3306:3306"

  app:
    image: otp2-shopping-cart:headless
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: shopping_cart_db
      DB_USER: root
      DB_PASSWORD: 9642
